### ISSUE TITLE
criação de um discord

### ISSUE THREAD

**Issue by TheusBoot** [hansalemaos/lxml2pandas#1]
seria muito bom, criar um discord para falamos sobre o projeto de (odds), além disso, poderia por mais pessoas para contribuir no projeto;

-Criação de automação para apostar entre 2/3 times, deixando assim, tudo 100% automático...
- Criação de um programa para por em produção, com interface etc...

**Comment by hansalemaos** [comment]
Obrigado pela sugestão. Quando tiver um pouco mais tempo, vou fazer :) Atualmente, estou preparando uns vídeos para YouTube e esse pacote vai fazer parte. É muuuuuuuuuuuuuuito rápido para raspar dados.

**Comment by TheusBoot** [comment]
muito bom, eu gostaria de te ajudar de alguma forma, pois eu também, tenho ideia de tá pegando esses dados e fazendo entrada automática, assim que chega odds batendo...

uma coisa que não entendi, nesse caso, a matemática que vc vai usar é diferente da https://oddspedia.com/br/apostas-certas ?

que no caso, ela simplesmente, ver (2) a (3) odds e depois a combina entre si para no fim ter um resultado equivalente

por exemplo
team1 vs team2 
odd1 = 2.40
odd2 = 2.50
apostando no dois time nesse formato;
APOSTA TOTAL R$50
odd1(R$ 25,51)
odd2(R$ 24,49)

qualquer um dos dois times ganhar, eu fico com (22.45%) de abritagem ou seja, fico com 11,23
VALOR FINAL(11,23)

porem se da empate, eu perco tudo kkkkkkkkkkk

porém, podemos aplicar a mesma lógica, colocando o empate no meio, ficaria assim;
team1 = 3.12
empate = 4.02
team2 = 3.50

---------------------------------------------------------------------------------------------------------------

team1 = R$ 37,49
empate = R$ 29.09
team2 = R$ 33,42

com qualquer desses 3 resultados dando, eu ficaria no lucro.(abritagem=16,96%) - LUCRO CERTO(16,96)
VALOR TOTAL 116,96

código a baixo em py


```python
Valor_total = 100

# Cotações das opções
casa_cotacao = 3.13
empate_cotacao = 3.81
fora_cotacao = 2.88

# Calculando o valor das apostas em cada opção para obter lucro independente do resultado
valor_casa = (valor_total / casa_cotacao) / (1 / casa_cotacao + 1 / empate_cotacao + 1 / fora_cotacao)
valor_empate = (valor_total / empate_cotacao) / (1 / casa_cotacao + 1 / empate_cotacao + 1 / fora_cotacao)
valor_fora = (valor_total / fora_cotacao) / (1 / casa_cotacao + 1 / empate_cotacao + 1 / fora_cotacao)

# Calculando o lucro certo


# Calculando o retorno de cada aposta
retorno_casa = valor_casa * casa_cotacao
retorno_empate = valor_empate * empate_cotacao
retorno_fora = valor_fora * fora_cotacao

valores_retorno = [retorno_casa, retorno_empate, retorno_fora]
#maior_retorno = max(valores_retorno)

porcentagem_diferenca = ((max(valores_retorno) - valor_total) / valor_total) * 100

lucro_certo = max(valores_retorno) - valor_total


# Imprimindo os resultados
print("Valor na casa:", round(valor_casa, 2))
print("Valor no empate:", round(valor_empate, 2))
print("Valor no fora:", round(valor_fora, 2))
print("Retorno da aposta na casa:", round(retorno_casa, 2))
print("Retorno da aposta no empate:", round(retorno_empate, 2))
print("Retorno da aposta no fora:", round(retorno_fora, 2))
print("abritagem:", round(porcentagem_diferenca, 2), "%")
print("Lucro certo:", round(lucro_certo, 2))```
